// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Ekc8asiz3xbR7abN6A_Zgh2B7Zm-8Uo',
    appId: '1:63151617314:web:819f20212b60064905217b',
    messagingSenderId: '63151617314',
    projectId: 'bibliodam-app',
    authDomain: 'bibliodam-app.firebaseapp.com',
    storageBucket: 'bibliodam-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDTU8nwGLwX0SYx96fMDQ8G8NGvszHllE',
    appId: '1:63151617314:android:35cab5f07c70a72405217b',
    messagingSenderId: '63151617314',
    projectId: 'bibliodam-app',
    storageBucket: 'bibliodam-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEyZmETGp_1EFewIByep6c33tFjizUZbA',
    appId: '1:63151617314:ios:5fabe244167731bd05217b',
    messagingSenderId: '63151617314',
    projectId: 'bibliodam-app',
    storageBucket: 'bibliodam-app.appspot.com',
    iosBundleId: 'com.example.bibliodamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEyZmETGp_1EFewIByep6c33tFjizUZbA',
    appId: '1:63151617314:ios:5fabe244167731bd05217b',
    messagingSenderId: '63151617314',
    projectId: 'bibliodam-app',
    storageBucket: 'bibliodam-app.appspot.com',
    iosBundleId: 'com.example.bibliodamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Ekc8asiz3xbR7abN6A_Zgh2B7Zm-8Uo',
    appId: '1:63151617314:web:724e0f36b1a8c7da05217b',
    messagingSenderId: '63151617314',
    projectId: 'bibliodam-app',
    authDomain: 'bibliodam-app.firebaseapp.com',
    storageBucket: 'bibliodam-app.appspot.com',
  );
}
